apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 904982166462.dkr.ecr.us-east-1.amazonaws.com/inventarios-frontend:v1
          ports:
            - containerPort: 8080
          env:
            # PENDIENTE: reemplazar por la URL real del backend-service
            # una vez que su LoadBalancer tenga hostname asignado.
            - name: API_URL
              value: "http://PENDIENTE-backend-lb-hostname:8080/api"
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
